import Footer from "../components/footer";
import Header from "../components/header";
import FacQuestions from "../components/produtos/FacQuestions";
import Hero from "../components/produtos/Hero";
import HeroDouble from "../components/produtos/HeroDouble";
import HeroReverse from "../components/produtos/HeroReverse";
import FeaturesTwo from "../components/quemsomoscomponent/featurestwo";


export default function Rufos() {
    return (
        <div>
            <Header />
                <Hero title="Rufos em Araucária: Proteção Duradoura para Comércios, Lojas e Indústrias" subTitle="Aço Galvanizado de Alta Qualidade para Garantir Resistência e Estilo" description="Com os rufos de aço galvanizado da Fabricalhas em Araucária, sua empresa não só ganha proteção contra as intempéries, mas também adiciona um toque de elegância ao visual de qualquer edifício comercial ou industrial. Fabricados com materiais de alta qualidade, nossos rufos são projetados para suportar os desafios climáticos e garantir a integridade estrutural por muitos anos.
                " Img="/Rufos/1.webp" />
                
                <HeroDouble title="Rufos em Araucária: Proteção Sob Medida para Residências" description="Qualidade Superior em Aço Galvanizado para Rufos Personalizados" text="Os rufos da Fabricalhas em Araucária são a solução ideal para quem busca proteção duradoura e personalizada para sua residência. Produzidos com aço galvanizado de alta qualidade, nossos rufos oferecem uma proteção confiável contra intempéries e infiltrações de água, garantindo a integridade de sua casa." secondText="Nossa equipe especializada fabrica rufos sob medida, assegurando que cada peça seja projetada de acordo com as necessidades específicas de sua propriedade. Seja para cobrir telhados, proteger paredes laterais ou oferecer acabamento em cantos e saliências, nossos rufos são feitos para se encaixar perfeitamente em sua residência." extraText="Além da durabilidade e funcionalidade proporcionadas pelo aço galvanizado, nossos rufos também têm um design moderno e elegante, complementando a estética da sua casa. O compromisso da Fabricalhas com a excelência vai além da fabricação – nossa equipe realiza instalações precisas e eficientes, garantindo que os rufos não apenas protejam sua residência, mas também melhorem sua aparência arquitetônica." extraText2="Na Fabricalhas, sabemos o quanto é importante proteger seu lar. Por isso, investimos na qualidade de nossos produtos e serviços, garantindo a sua satisfação total. Confie em nós para fornecer rufos sob medida em Araucária, atendendo às suas necessidades e trazendo tranquilidade e segurança para sua casa." firstImg={'/Rufos/2.webp'} secondImg={'/Rufos/3.webp'} />

                <HeroReverse title="Proteção Contra Infiltrações: Maximize a Eficiência com Rufos em Araucária" description="Aplicação Estratégica de Aço Galvanizado pela Fabricalhas" text="Na prevenção de infiltrações e danos causados pela umidade, os rufos em Araucária de aço galvanizado da Fabricalhas se destacam como uma solução eficiente e duradoura. Desenvolvidos para proteger áreas estratégicas em edificações comerciais, residenciais e industriais, nossos rufos são essenciais para manter a integridade estrutural e a segurança de sua propriedade." secondText="" extraText="" extraText2="" firstImg={'/Rufos/4.webp'} secondImg={'/Rufos/5.webp'} />


                <HeroDouble title="Rufos em Araucária: Proteção Duradoura para Muros" description="Aço Galvanizado de Qualidade Superior pela Fabricalhas" text="Os rufos em Araucária da Fabricalhas, fabricados com aço galvanizado de alta qualidade, oferecem proteção confiável e duradoura para os muros de sua propriedade. Projetados para resistir aos elementos climáticos, esses rufos protegem os muros contra os danos causados pela umidade e intempéries.
                " secondText="Instalados nas bordas superiores dos muros, os rufos impedem que a água da chuva escorra pelas paredes, evitando a formação de manchas, mofo e outros problemas relacionados à umidade. Isso preserva a estética do muro e garante sua integridade estrutural a longo prazo." extraText="Fabricados com materiais resistentes à corrosão, nossos rufos asseguram durabilidade excepcional, mesmo em condições adversas. Também oferecemos opções personalizadas, para que os rufos se ajustem perfeitamente às dimensões e ao estilo de seu muro, proporcionando não apenas proteção eficaz, mas também um acabamento estético impecável.
                " extraText2="Na Fabricalhas, nossa equipe especializada garante uma instalação precisa e eficiente dos rufos, assegurando que sua propriedade receba a proteção necessária, sem comprometer sua aparência visual. Confie na Fabricalhas para fornecer rufos de alta qualidade, que preservam e protegem os muros de sua propriedade, mantendo sua beleza e durabilidade por muitos anos." firstImg={'/Rufos/6.webp'} secondImg={'/Rufos/7.webp'} />

                <HeroReverse title="Rufos em Araucária: Proteção Essencial para Chaminés" description="Durabilidade e Eficiência com Aço Galvanizado pela Fabricalhas" text="Os rufos em Araucária da Fabricalhas, fabricados com aço galvanizado de alta qualidade, são a solução ideal para proteger suas chaminés contra os danos causados pela umidade e intempéries. Projetados com precisão, esses rufos oferecem uma vedação duradoura e eficaz ao redor da base da chaminé, prevenindo vazamentos e danos estruturais." secondText="Instalados com atenção aos detalhes, nossos rufos formam uma barreira segura contra a entrada de água, evitando a corrosão e o desgaste precoce da estrutura da chaminé. Além disso, protegem as paredes adjacentes da infiltração de umidade, garantindo a integridade de toda a construção." extraText="Fabricados com materiais resistentes à corrosão, nossos rufos oferecem uma durabilidade excepcional, mesmo em condições climáticas severas. Oferecemos também opções personalizadas, garantindo que os rufos se ajustem perfeitamente às dimensões e estilo da sua chaminé, proporcionando uma proteção eficiente e um acabamento visual impecável.
                " extraText2="Na Fabricalhas, nossa equipe especializada realiza a instalação precisa e eficiente de seus rufos, assegurando que sua chaminé seja protegida sem comprometer a estética do telhado ou da propriedade. Confie na Fabricalhas para fornecer rufos de qualidade superior que garantem a durabilidade e funcionalidade da sua chaminé por muitos anos." firstImg={'/Rufos/8.webp'} secondImg={'/Rufos/9.webp'} /> 

                <HeroDouble title="Produtos e Serviços" description="Serviços de Calheiro em Araucária – Solicite um Orçamento!" text="Na Fabricalhas, contamos com uma equipe de profissionais altamente capacitados, com todos os cursos de especialização necessários no mercado, incluindo NR18, NR35 e NR38, garantindo a máxima qualidade em nossos serviços." secondText="Oferecemos uma ampla variedade de serviços, sempre com zelo, cuidado e profissionalismo, visando proporcionar a total satisfação do cliente e a confiança em um serviço bem executado." extraText="Nossos produtos são fabricados internamente, utilizando matéria-prima nacional de altíssima qualidade, em conjunto com equipamentos modernos. Isso resulta em um excelente custo-benefício para nossos clientes, sempre priorizando eficiência e durabilidade." firstImg={'/Rufos/10.webp'} secondImg={'/Rufos/11.webp'} />

                <HeroReverse title="Rufo Pingadeira em Araucária: Proteção Contra Infiltrações" description="Durabilidade e Eficiência com Aço Galvanizado da Fabricalhas" text="O rufo pingadeira em Araucária de aço galvanizado da Fabricalhas é a solução ideal para proteger sua construção contra infiltrações e danos causados pela umidade. Instalado nas bordas inferiores do telhado, ele impede que a água da chuva escorra pelas paredes externas, prevenindo diversos problemas estruturais.
                " secondText="Desenvolvido com precisão, o rufo pingadeira em Araucária oferece excelente durabilidade e eficácia, criando uma barreira contra a entrada de água nos pontos mais vulneráveis da sua construção. Isso ajuda a evitar danos como manchas, mofo, corrosão e outros efeitos negativos da umidade.
                " extraText="A utilização de aço galvanizado garante resistência à corrosão e longa vida útil, mesmo em condições climáticas adversas. Na Fabricalhas, também oferecemos opções personalizadas para que o rufo se ajuste perfeitamente ao estilo e dimensões do seu telhado, proporcionando proteção eficaz e um acabamento visual impecável." extraText2="Com uma equipe qualificada e experiente, garantimos a instalação segura e precisa do rufo pingadeira, assegurando que sua propriedade esteja bem protegida contra infiltrações e danos causados pela umidade. Confie na Fabricalhas para entregar produtos de qualidade superior, preservando a integridade e a estética de sua construção por muitos anos." firstImg={'/Rufos/12.webp'} secondImg={'/Rufos/1.webp'} />

                <FacQuestions Q1="Quais são os benefícios dos rufos em Araucária de aço galvanizado?" R1="Os rufos em Araucária de aço galvanizado oferecem durabilidade, resistência à corrosão e proteção eficaz contra infiltrações de água." Q2="Como os rufos para chaminés podem proteger minha casa?" R2="Os rufos para chaminés evitam a entrada de água na estrutura, prevenindo danos causados pela umidade e prolongando a vida útil da chaminé." Q3="Qual a função dos rufos para paredes?" R3="Os rufos para paredes impedem que a água da chuva escorra pelas paredes, protegendo contra danos e infiltrações." Q4="O que são rufos para coifas e como são aplicados?" R4="Os rufos para coifas são instalados ao redor das saídas de ar das cozinhas, garantindo uma vedação eficaz e evitando infiltrações de água." Q5="Quais os diferenciais dos rufos da Fabricalhas para residências?" R5="Os rufos da Fabricalhas são fabricados sob medida, garantindo uma instalação precisa e eficaz para proteção duradoura." Q6="Como os rufos para comércios contribuem para a segurança do estabelecimento?" R6="Os rufos para comércios evitam danos estruturais causados pela água, protegendo assim o patrimônio e garantindo a segurança dos clientes e funcionários." Q7="Quais os benefícios dos rufos para lojas em termos estéticos?" R7="Os rufos para lojas oferecem um acabamento elegante e profissional, contribuindo para a estética do estabelecimento e atraindo clientes." Q8="Como os rufos para indústrias protegem os equipamentos e maquinários?" R8="Os rufos para indústrias evitam a entrada de água nos ambientes internos, protegendo equipamentos sensíveis e reduzindo o risco de danos." Q9="Por que os galpões precisam de rufos de alta qualidade?" R9="Os rufos para galpões garantem a proteção das estruturas contra vazamentos e corrosão, prolongando assim a vida útil do edifício." Q10="A instalação dos rufos em Araucária é complexa?" R10="Não, a instalação dos rufos em Araucária é relativamente simples, especialmente quando realizada por profissionais qualificados, como os da Fabricalhas, garantindo assim um resultado seguro e duradouro." />
            <Footer />
        </div>
    )
}


{/* <HeroReverse title="" description="" text="" secondText="" extraText="" extraText2=""  /> */}